package View;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class View_ThongKe extends JFrame {
    public View_ThongKe() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            initComponents();
        LuotMuonThang.setVisible(false);
        SVTraSachTre.setVisible(false);
        SachTreHen.setVisible(false);
        SachmuontheoSV.setVisible(false);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            jPanel2 = new javax.swing.JPanel();
            SVTraSachTre = new javax.swing.JPanel();
            jLabel3 = new javax.swing.JLabel();
            jScrollPane2 = new javax.swing.JScrollPane();
            SVTre = new javax.swing.JTable();
            jSeparator3 = new javax.swing.JSeparator();
            jLabel10 = new javax.swing.JLabel();
            SachmuontheoSV = new javax.swing.JPanel();
            jTextField1 = new javax.swing.JTextField();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jScrollPane3 = new javax.swing.JScrollPane();
            Muontheosv = new javax.swing.JTable();
            jSeparator5 = new javax.swing.JSeparator();
            jLabel12 = new javax.swing.JLabel();
            LuotMuonThang = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            thang = new javax.swing.JComboBox<>();
            jScrollPane1 = new javax.swing.JScrollPane();
            MuonThang = new javax.swing.JTable();
            thang1 = new javax.swing.JComboBox<>();
            jLabel8 = new javax.swing.JLabel();
            jSeparator4 = new javax.swing.JSeparator();
            jLabel7 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            SachTreHen = new javax.swing.JPanel();
            jLabel6 = new javax.swing.JLabel();
            jScrollPane4 = new javax.swing.JScrollPane();
            sachtrehen = new javax.swing.JTable();
            jSeparator2 = new javax.swing.JSeparator();
            jLabel11 = new javax.swing.JLabel();
            menu = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jButton0 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            jSeparator1 = new javax.swing.JSeparator();
            jButton4 = new javax.swing.JButton();
            jLabel13 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(204, 255, 204));
            setBounds(new java.awt.Rectangle(600, 800, 0, 0));
            setSize(new java.awt.Dimension(800, 800));
            setLocation(400,40);
            SVTraSachTre.setBackground(new java.awt.Color(255, 255, 153));

            jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel3.setText("DANH SÁCH SINH VIÊN TRẢ SÁCH TRỄ HẸN");

            SVTre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            SVTre.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                            {null, null},
                            {null, null},
                            {null, null},
                            {null, null},
                            {null, null},
                            {null, null}
                    },
                    new String [] {
                            "Mã sinh viên", "Số lượng sách"
                    }
            ));
            jScrollPane2.setViewportView(SVTre);

            jSeparator3.setForeground(new java.awt.Color(153, 0, 204));
            jSeparator3.setMinimumSize(new java.awt.Dimension(50, 20));

            //jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/teamwork.png"))); // NOI18N

            javax.swing.GroupLayout SVTraSachTreLayout = new javax.swing.GroupLayout(SVTraSachTre);
            SVTraSachTre.setLayout(SVTraSachTreLayout);
            SVTraSachTreLayout.setHorizontalGroup(
                    SVTraSachTreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SVTraSachTreLayout.createSequentialGroup()
                                    .addContainerGap(159, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addGroup(SVTraSachTreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(216, 216, 216))
                            .addGroup(SVTraSachTreLayout.createSequentialGroup()
                                    .addGap(167, 167, 167)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            SVTraSachTreLayout.setVerticalGroup(
                    SVTraSachTreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SVTraSachTreLayout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addGroup(SVTraSachTreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(SVTraSachTreLayout.createSequentialGroup()
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel10))
                                    .addGap(35, 35, 35)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(43, Short.MAX_VALUE))
            );

            SachmuontheoSV.setBackground(new java.awt.Color(204, 255, 204));

            jTextField1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField1ActionPerformed(evt);
                }
            });

            jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel4.setText("SÁCH MƯỢN CỦA SINH VIÊN");

            jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            //jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man.png"))); // NOI18N
            jLabel5.setText("MSV:");

            //jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N

            Muontheosv.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                            {null, null, null, null, null, null},
                            {null, null, null, null, null, null},
                            {null, null, null, null, null, null},
                            {null, null, null, null, null, null}
                    },
                    new String [] {
                            "Mã sách", "Tên sách", "Giá", "Số lượng", "Ngày mượn", "Ngày hẹn trả"
                    }
            ));
            jScrollPane3.setViewportView(Muontheosv);

            jSeparator5.setForeground(new java.awt.Color(255, 153, 255));

           // jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/people.png"))); // NOI18N

            javax.swing.GroupLayout SachmuontheoSVLayout = new javax.swing.GroupLayout(SachmuontheoSV);
            SachmuontheoSV.setLayout(SachmuontheoSVLayout);
            SachmuontheoSVLayout.setHorizontalGroup(
                    SachmuontheoSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SachmuontheoSVLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addGroup(SachmuontheoSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(SachmuontheoSVLayout.createSequentialGroup()
                                                    .addGap(25, 25, 25)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap(22, Short.MAX_VALUE))
                            .addGroup(SachmuontheoSVLayout.createSequentialGroup()
                                    .addGap(185, 185, 185)
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addGroup(SachmuontheoSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(SachmuontheoSVLayout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))
            );
            SachmuontheoSVLayout.setVerticalGroup(
                    SachmuontheoSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SachmuontheoSVLayout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addGroup(SachmuontheoSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(SachmuontheoSVLayout.createSequentialGroup()
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel12))
                                    .addGap(18, 18, 18)
                                    .addGroup(SachmuontheoSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addGroup(SachmuontheoSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5)))
                                    .addGap(28, 28, 28)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(42, Short.MAX_VALUE))
            );

            LuotMuonThang.setBackground(new java.awt.Color(204, 204, 255));

            jLabel2.setBackground(new java.awt.Color(255, 255, 102));
            jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(51, 51, 0));
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("THỐNG KÊ LƯỢT MƯỢN THEO THÁNG");

            thang.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
            thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12" }));
//            thang.addActionListener(new java.awt.event.ActionListener() {
//                public void actionPerformed(java.awt.event.ActionEvent evt) {
//                    thangActionPerformed(evt);
//                }
//            });

            MuonThang.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                            {null, null, null, null, null, null},
                            {null, null, null, null, null, null},
                            {null, null, null, null, null, null},
                            {null, null, null, null, null, null}
                    },
                    new String [] {
                            "Mã sinh viên", "Mã Sách", "Ngày mượn", "Ngày hẹn trả", "Số Lượng", "QLTV"
                    }
            ));
            jScrollPane1.setViewportView(MuonThang);

            thang1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
            thang1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm 2022", "Năm 2023" }));

            //jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calendar.png"))); // NOI18N

            jSeparator4.setForeground(new java.awt.Color(255, 255, 153));
            jSeparator4.setMinimumSize(new java.awt.Dimension(50, 20));

           // jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/to-do-list.png"))); // NOI18N

            javax.swing.GroupLayout LuotMuonThangLayout = new javax.swing.GroupLayout(LuotMuonThang);
            LuotMuonThang.setLayout(LuotMuonThangLayout);
            LuotMuonThangLayout.setHorizontalGroup(
                    LuotMuonThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LuotMuonThangLayout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addGroup(LuotMuonThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(215, 215, 215))
                            .addGroup(LuotMuonThangLayout.createSequentialGroup()
                                    .addGroup(LuotMuonThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(LuotMuonThangLayout.createSequentialGroup()
                                                    .addGap(14, 14, 14)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(LuotMuonThangLayout.createSequentialGroup()
                                                    .addGap(56, 56, 56)
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(thang, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(thang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addContainerGap(22, Short.MAX_VALUE))
            );
            LuotMuonThangLayout.setVerticalGroup(
                    LuotMuonThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LuotMuonThangLayout.createSequentialGroup()
                                    .addGroup(LuotMuonThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(LuotMuonThangLayout.createSequentialGroup()
                                                    .addGap(58, 58, 58)
                                                    .addGroup(LuotMuonThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel7))
                                                    .addGap(9, 9, 9)
                                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(10, 10, 10))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LuotMuonThangLayout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(jLabel9)
                                                    .addGap(21, 21, 21)))
                                    .addGroup(LuotMuonThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(LuotMuonThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(thang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(37, Short.MAX_VALUE))
            );

            SachTreHen.setBackground(new java.awt.Color(255, 204, 204));
            SachTreHen.setForeground(new java.awt.Color(51, 0, 0));

            jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel6.setText("DANH SÁCH CÁC ĐẦU SÁCH BỊ TRẢ TRỄ HẸN");

            sachtrehen.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null}
                    },
                    new String [] {
                            "Mã sách", "Tên sách", "Giá", "Số lượng"
                    }
            ));
            jScrollPane4.setViewportView(sachtrehen);

            jSeparator2.setForeground(new java.awt.Color(153, 255, 153));

           // jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/books.png"))); // NOI18N

            javax.swing.GroupLayout SachTreHenLayout = new javax.swing.GroupLayout(SachTreHen);
            SachTreHen.setLayout(SachTreHenLayout);
            SachTreHenLayout.setHorizontalGroup(
                    SachTreHenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SachTreHenLayout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addGroup(SachTreHenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(SachTreHenLayout.createSequentialGroup()
                                                    .addGap(99, 99, 99)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(SachTreHenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addContainerGap(40, Short.MAX_VALUE))
            );
            SachTreHenLayout.setVerticalGroup(
                    SachTreHenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SachTreHenLayout.createSequentialGroup()
                                    .addContainerGap(62, Short.MAX_VALUE)
                                    .addGroup(SachTreHenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SachTreHenLayout.createSequentialGroup()
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(44, 44, 44)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52))
            );

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SachTreHen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LuotMuonThang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SachmuontheoSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SVTraSachTre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SachTreHen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LuotMuonThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SachmuontheoSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SVTraSachTre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            menu.setBackground(new java.awt.Color(204, 255, 204));

            jLabel1.setBackground(new java.awt.Color(255, 153, 153));
            jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(0, 51, 51));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("THỐNG KÊ - BÁO CÁO");

            jButton0.setText("Danh sách sinh viên tra sách muộn");
            jButton0.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    System.out.println("JButton0");
                }
            });
            jButton1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    System.out.println("JBtn1");
                }
            });
            jButton2.setText("Danh sách Sách trả muộn");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jButton3.setText("Danh sách lượt mượn theo tháng");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            jSeparator1.setForeground(new java.awt.Color(255, 204, 204));

            jButton4.setText("Sách mượn theo sinh viên");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });

           // jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/statistics.png"))); // NOI18N

            javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
            menu.setLayout(menuLayout);
            menuLayout.setHorizontalGroup(
                    menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jButton2)
                                    .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                                    .addContainerGap(25, Short.MAX_VALUE)
                                    .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                                                    .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                                                                    .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(menuLayout.createSequentialGroup()
                                                                                    .addGap(6, 6, 6)
                                                                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                            .addComponent(jLabel1))
                                                                    .addGap(9, 9, 9))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jButton3)
                                                                    .addComponent(jButton0)
                                                                    .addGroup(menuLayout.createSequentialGroup()
                                                                            .addGap(65, 65, 65)
                                                                            .addComponent(jLabel13))))
                                                    .addGap(15, 15, 15))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                                                    .addComponent(jButton4)
                                                    .addGap(37, 37, 37))))
            );
            menuLayout.setVerticalGroup(
                    menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLayout.createSequentialGroup()
                                    .addGap(72, 72, 72)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton0)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton4)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>

        private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            SVTraSachTre.setVisible(true);
            LuotMuonThang.setVisible(false);
            SachTreHen.setVisible(false);
            SachmuontheoSV.setVisible(false);
        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            LuotMuonThang.setVisible(false);
            SVTraSachTre.setVisible(false);
            SachTreHen.setVisible(true);
            SachmuontheoSV.setVisible(false);
        }

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            LuotMuonThang.setVisible(true);
            SVTraSachTre.setVisible(false);
            SachTreHen.setVisible(false);
            SachmuontheoSV.setVisible(false);
        }

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            LuotMuonThang.setVisible(false);
            SVTraSachTre.setVisible(false);
            SachTreHen.setVisible(false);
            SachmuontheoSV.setVisible(true);
        }

        private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }

        private void thangActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            new View_ThongKe().setVisible(true);
        }


        // Variables declaration - do not modify
        private static javax.swing.JPanel LuotMuonThang;
        private static javax.swing.JPanel SVTraSachTre;
        private static javax.swing.JPanel SachTreHen;
        private static javax.swing.JPanel SachmuontheoSV;
        public javax.swing.JButton jButton0;
        public javax.swing.JButton jButton1;
        public javax.swing.JButton jButton2;
        public javax.swing.JButton jButton3;
        public javax.swing.JButton jButton4;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JSeparator jSeparator3;
        private javax.swing.JSeparator jSeparator4;
        private javax.swing.JSeparator jSeparator5;
        public javax.swing.JTable MuonThang;
        public javax.swing.JTable SVTre;
        public javax.swing.JTable Muontheosv;
        public javax.swing.JTable sachtrehen;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JPanel menu;
        private javax.swing.JComboBox<String> thang;
        private javax.swing.JComboBox<String> thang1;
        // End of variables declaration
    }


